# Generated by Django 5.0.7 on 2024-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_customuser_groups_customuser_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Member", "Member")], max_length=20
            ),
        ),
    ]
